### ISSUE TITLE
How do you access the pins via "PDX" for the 100?

### ISSUE THREAD

**Issue by AyrtonRicardo** [cpxazn/klipper_config#1]
Opening this issues just to know how were you able to access the pins via its aliases instead of "gpiox"... For example PD0 instead of gpio9

THank you.
Very insightful repository for my the100 printer.

**Comment by cpxazn** [comment]
This varies between mainboards. You would need to lookup the pins diagram for each mainboard to find out.
[SKR Pico](https://github.com/bigtreetech/SKR-Pico/blob/master/Hardware/BTT%20SKR%20Pico%20V1.0-PIN.pdf) goes by IOXX
[MKS Monster8](https://github.com/makerbase-mks/MKS-Monster8/blob/main/hardware/MKS%20Monster8%20V1.0_003/MKS%20Monster8%20V1.0_003%20PIN.pdf) goes by PXX

**Comment by AyrtonRicardo** [comment]
> This varies between mainboards. You would need to lookup the pins diagram for each mainboard to find out. [SKR Pico](https://github.com/bigtreetech/SKR-Pico/blob/master/Hardware/BTT%20SKR%20Pico%20V1.0-PIN.pdf) goes by IOXX [MKS Monster8](https://github.com/makerbase-mks/MKS-Monster8/blob/main/hardware/MKS%20Monster8%20V1.0_003/MKS%20Monster8%20V1.0_003%20PIN.pdf) goes by PXX

Okay, I thought you were using pico, that's clear, thank you!
